### ISSUE TITLE
cEP-0017: Bears Package Manager

### ISSUE THREAD

**Issue by sims1253** [coala/cEPs#10]
sooo you want a conda cep i think :D
@sils1297

**Comment by sils** [comment]
CC @Adrianzatreanu

**Comment by Adrianzatreanu** [comment]
im a little confused regarding this issue. could you elaborate? 

too little info given.

**Comment by sils** [comment]
this issue was created so we would have a cEP describing cib, the cEPs could also act as user documentation which is why this is still open

**Comment by Adrianzatreanu** [comment]
scary issue

**Comment by jayvdb** [comment]
Using conda allows solving
the Python 2 vs 3 bears problem.

**Comment by jayvdb** [comment]
One existing tool which might provide similar functionality is https://github.com/mbodenhamer/depman .  It should be considered as part of this cEP.

c.f. https://gitlab.com/coala/package_manager/issues/149
