### ISSUE TITLE
coala is written with a lowercase 'c'

### ISSUE THREAD

**Issue by nvzard** [coala/cEPs#111]
Many cEP titles have mentioned 'Coala' instead of 'coala'

https://github.com/coala/cEPs/blob/master/README.md

**Comment by JameerBabu** [comment]
Hello,

I am new to coala. I want to contribute to it. So, as a newbie I would like to fix this to boost my confidence. Can you please assign this issue to me.

**Comment by jayvdb** [comment]
@JameerBabu , I've sent you an invite to this GitHub org.  Please accept.

**Comment by JameerBabu** [comment]
Hi John,

I have accepted the invitation and joined successfully in the group. Now, can you please assign this issue to me.
