### ISSUE TITLE
README.md: Typo, 'mechnaism' should be 'mechanism'

### ISSUE THREAD

**Issue by refeed** [coala/cEPs#115]
Typo in `README.md`, 'mechnaism' should be 'mechanism' in line 15

**Comment by devesh-verma** [comment]
@jayvdb can I work in this? 😃

**Comment by jayvdb** [comment]
@devshiva619 , no , you have already done a newcomer issue.  Please choose a http://coala.io/low difficulty issue to work on.

**Comment by Yagya-Chaudhary** [comment]
Is it fine now?

**Comment by Yagya-Chaudhary** [comment]
Done .
