### ISSUE TITLE
.coafile Set line length

### ISSUE THREAD

**Issue by jayvdb** [coala/cEPs#134]
https://github.com/coala/cEPs/pull/131 's https://github.com/coala/cEPs/pull/131/commits/86160dc8bf21f4e5b3c7f6f69ab3a7e82104cf20 passes gitmate, but has length > 80

MarkdownBear has a max line length setting.
If it doesnt work, use LineLengthBear.

**Comment by blazeu** [comment]
[MarkdownBear](https://github.com/coala/coala-bears/blob/master/bears/markdown/MarkdownBear.py#L68) has `max_line_length` set to `None` as default, but I did get error when having length > 80.

Hmm, is it possible that I'm using old version of MarkdownBear when making https://github.com/coala/cEPs/pull/128 ?
That explains this issue about inconsistency https://github.com/coala/cEPs/pull/128#issuecomment-387789944

**Comment by ankitxjoshi** [comment]
Assign it to me.
