### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by sks444** [coala/cEPs#135]
Add `.gitignore` file with ignoring `orig` files.

**Comment by RaiVaibhav** [comment]
`*.orig`

**Comment by jayvdb** [comment]
Use moban's gitignore template.
See other repositories, and the many open PRs. about it

**Comment by dkopatz** [comment]
@jayvdb does that mean that i can take the .gitignore file from for example coala/coala?

**Comment by hrithik-jha** [comment]
If it's still unattended, I can try this out.

**Comment by Utkarsh1308** [comment]
Can I be assigned to this please

**Comment by jayvdb** [comment]
This issue must create a .moban.yaml file which uses moban to fetch the coala default .gitignore file.

@Utkarsh1308, you can not work on this until your first patch is merged.

**Comment by Utkarsh1308** [comment]
Can I be assigned to this issue now?

**Comment by jayvdb** [comment]
sure.

but you dont need a custom template.  you can use `coala-gitignore.jj2`
