### ISSUE TITLE
I want to be allowed to write cEP-8 instead of cEP-0008 :(

### ISSUE THREAD

**Issue by underyx** [coala/cEPs#16]

**Comment by Makman2** [comment]
does it really matter that hard? :P

**Comment by sils** [comment]
yes!

**Comment by sils** [comment]
why should we not allow it

**Comment by Makman2** [comment]
Honestly I don't care :P

**Comment by Mariatta** [comment]
Is this same as https://github.com/coala/cEPs/issues/57 ?

**Comment by underyx** [comment]
Yep

**Comment by sils** [comment]
Goal here is to modify cEP-0000 to make this possible.

**Comment by arnab1896** [comment]
If we modify cEP-0000; then do we also have to change ALL occurrences of cEP-#### in the entire repository? Starting from cEP-0000 to cEP-0006 and change all of them to cEP-0 to cEP-6?

**Comment by aptrishu** [comment]
Or maybe allow both format ?

**Comment by sils** [comment]
Allow both IMO
