### ISSUE TITLE
AST project clarification

### ISSUE THREAD

**Issue by jayvdb** [coala/cEPs#169]
Can the ANTLR ast be used to do fixes?

The cEP isnt clear on this.

The pyflakes cEP also isnt clear ... this should be in the intro .. but it does have an example

https://github.com/coala/cEPs/blob/master/cEP-0025.md#demonstrating-use-of-pyflakesastbear-by-creating-a-simple-bear

**Comment by ankitxjoshi** [comment]
Would create a patch to include this in intro.
