### ISSUE TITLE
Make a cEP on memberization and dememberization

### ISSUE THREAD

**Issue by sils** [coala/cEPs#23]
IMO:
- making members as we do know (jsut write it down)
- dememberize any member that hasn't done a contribution within the last three months. This should be evaluated for all members every three months.A "Contribution" is rather loosely defined on purpose. There should be a committee taking care of this and deciding what counts and what doesn't. If members disagree they can of course make a B (or C) level decision.

Any opinions? @sims1253 ?

**Comment by sils** [comment]
- the member may argue against a dememberization and it's within the freedom of the commitee to accept that if the argument makes sense

**Comment by Mariatta** [comment]
> dememberize any member that hasn't done a contribution within the last three months. This should be evaluated for all members every three months.A "Contribution" is rather loosely defined on purpose. There should be a committee taking care of this and deciding what counts and what doesn't. If members disagree they can of course make a B (or C) level decision.


+1

**Comment by sims1253** [comment]
will draft a cEP around christmas, first iteration before new year

But I think we could add this to the member cEP which is cEP-0001 i think and it doesn't need its own

**Comment by sims1253** [comment]
idea:
take away control of mail account but keep a fw after someone is dememberized

**Comment by sils** [comment]
IMO let im have his account, there's no cost to it. In case of conflict,
talk to each other.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by sims1253** [comment]
This also should include the developer "rank"
