### ISSUE TITLE
cEP1: Everybody should at all times be able to fork the project

### ISSUE THREAD

**Issue by fneu** [coala/cEPs#3]
> The community may at all times abandon the project and create a fork if the BLD acts stupidishly or is uncovered a fraud.

This can be interpreted as "the community MAY NOT abandon the project and create a fork UNLESS the bld acts stupidly or is uncovered a fraud"

Even though (or especially because) I don't expect this statement to be meant that way this should probably be changed...

and also "stupidishly" should probably be "stupidly"

**Comment by sils** [comment]
@fneu do you want this merged first? If so we would have to redo the vote.

**Comment by fneu** [comment]
Well, do we have to redo the vote if we merge it after? How many people 
need to agree?

Personally I don't care so I voted already.

Am 3. Juni 2016 7:24:14 nachm. schrieb Lasse Schuirmann 
notifications@github.com:

**Comment by sils** [comment]
since then cEP-1 is active we can just do a B vote, two people agreeing
would be fine

**Comment by fneu** [comment]
fine with me
