### ISSUE TITLE
Short-URL for cEPs need to be created

### ISSUE THREAD

**Issue by arnab1896** [coala/cEPs#65]
right now the only shortURL that works
is this one ---> coala.io/cep5

all the othere; i.e. coala.io/cep#

where # is 0 to 4 or 6 are re-directed to cEP-0000
difficulty/low

**Comment by shreyans800755** [comment]
I would like to work on this issue. But I don't know which project/file takes care of generating shortURL. Can anyone help me ?

**Comment by meetmangukiya** [comment]
@shreyans800755 not an issue that you can fix ;)

**Comment by vaishnavm217** [comment]
can i work on this? doesn't this require editing backend file?

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/devops/issues/85
