### ISSUE TITLE
cEP-0010.md: Fix a typo

### ISSUE THREAD

**Issue by khanchi97** [coala/cEPs#93]
In line 195 replace `max_identifier_length` with `min_identifier_length`

Difficulty/newcomer

**Comment by Makman2** [comment]
@khanchi97 Actually I'm not sure if this issue is valid, why do you want to remove those?

**Comment by Makman2** [comment]
(except the typo, that's definitely a mistake)

**Comment by Makman2** [comment]
Also it sounds like the issue can be split up into smaller issues ("remove text **and** fix typo")

**Comment by khanchi97** [comment]
>Actually I'm not sure if this issue is valid, why do you want to remove those?

@Makman2 text that has to be removed is repeated two times.

**Comment by ishanSrt** [comment]
@khanchi97 actually the text isn't repeated. look closely:

> Root.Formatting.Indentation: This taste checks on the number of space used for indentation given Root.Formatting.Indentation.size.

**Comment by khanchi97** [comment]
Oh, seems like I misunderstood the text.I have changed the title of issue.
